services:
  mock-service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mock-service
    container_name: mock-service
    environment:
      SECRET_KEY: "${SECRET_KEY:-test}"
    ports:
      - "8000:8000"

networks:
  guest:
